version: '3.7'

services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=admin
      #- SPLUNK_LICENSE_URI=http://example.com/splunk.lic
    volumes:
      - "var:/opt/splunk/var"
      - "etc:/opt/splunk/etc"
      - "./system_local/authentication.conf:/opt/splunk/etc/system/local/authentication.conf"
      - "./system_local/log-local.cfg:/opt/splunk/etc/log-local.cfg"
      - "./splunk_sample_app:/opt/splunk/etc/apps/splunk_sample_app"
    ports:
      - "8000:8000"
      - "8089:8089"

volumes:
  var:
  etc:
